name: panda3
channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pytorch=1.12.0
  - cudatoolkit=11.3
  - numpy
  - pandas
  - scipy
  - matplotlib
  - biopython
  - jupyter
  - pip
  - pip:
    - fair-esm==1.0.2
    - py3dmol==1.8.1
    - torch-geometric==2.0.4
    - torch-scatter==2.0.9
    - torch-sparse==0.6.14
    - tqdm
    - scikit-learn